// <auto-generated />
using BasicBilling.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasicBilling.API.Migrations
{
    [DbContext(typeof(BasicBillingDBContext))]
    [Migration("20210411204608_BasicBillingFirstMigration")]
    partial class BasicBillingFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13");

            modelBuilder.Entity("BasicBilling.API.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("BillStatus_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Client_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(25);

                    b.HasKey("BillId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            BillId = 1,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 1,
                            Client_Id = 1,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 2,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 1,
                            Client_Id = 1,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 3,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 1,
                            Client_Id = 1,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 4,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 1,
                            Client_Id = 1,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 5,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 2,
                            Client_Id = 1,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 6,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 2,
                            Client_Id = 1,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 7,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 2,
                            Client_Id = 1,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 8,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 2,
                            Client_Id = 1,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 9,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 3,
                            Client_Id = 1,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 10,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 3,
                            Client_Id = 1,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 11,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 3,
                            Client_Id = 1,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 12,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 3,
                            Client_Id = 1,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 13,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 1,
                            Client_Id = 2,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 14,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 1,
                            Client_Id = 2,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 15,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 1,
                            Client_Id = 2,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 16,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 1,
                            Client_Id = 2,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 17,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 2,
                            Client_Id = 2,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 18,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 2,
                            Client_Id = 2,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 19,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 2,
                            Client_Id = 2,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 20,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 2,
                            Client_Id = 2,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 21,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 3,
                            Client_Id = 2,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 22,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 3,
                            Client_Id = 2,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 23,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 3,
                            Client_Id = 2,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 24,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 3,
                            Client_Id = 2,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 25,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 1,
                            Client_Id = 3,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 26,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 1,
                            Client_Id = 3,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 27,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 1,
                            Client_Id = 3,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 28,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 1,
                            Client_Id = 3,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 29,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 2,
                            Client_Id = 3,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 30,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 2,
                            Client_Id = 3,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 31,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 2,
                            Client_Id = 3,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 32,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 2,
                            Client_Id = 3,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 33,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 3,
                            Client_Id = 3,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 34,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 3,
                            Client_Id = 3,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 35,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 3,
                            Client_Id = 3,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 36,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 3,
                            Client_Id = 3,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 37,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 1,
                            Client_Id = 4,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 38,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 1,
                            Client_Id = 4,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 39,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 1,
                            Client_Id = 4,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 40,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 1,
                            Client_Id = 4,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 41,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 2,
                            Client_Id = 4,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 42,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 2,
                            Client_Id = 4,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 43,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 2,
                            Client_Id = 4,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 44,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 2,
                            Client_Id = 4,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 45,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 3,
                            Client_Id = 4,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 46,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 3,
                            Client_Id = 4,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 47,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 3,
                            Client_Id = 4,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 48,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 3,
                            Client_Id = 4,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 49,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 1,
                            Client_Id = 5,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 50,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 1,
                            Client_Id = 5,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 51,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 1,
                            Client_Id = 5,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 52,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 1,
                            Client_Id = 5,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 53,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 2,
                            Client_Id = 5,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 54,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 2,
                            Client_Id = 5,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 55,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 2,
                            Client_Id = 5,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 56,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 2,
                            Client_Id = 5,
                            Period = 202104
                        },
                        new
                        {
                            BillId = 57,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 3,
                            Client_Id = 5,
                            Period = 202101
                        },
                        new
                        {
                            BillId = 58,
                            Amount = 0.0,
                            BillStatus_Id = 2,
                            Category_Id = 3,
                            Client_Id = 5,
                            Period = 202102
                        },
                        new
                        {
                            BillId = 59,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 3,
                            Client_Id = 5,
                            Period = 202103
                        },
                        new
                        {
                            BillId = 60,
                            Amount = 0.0,
                            BillStatus_Id = 1,
                            Category_Id = 3,
                            Client_Id = 5,
                            Period = 202104
                        });
                });

            modelBuilder.Entity("BasicBilling.API.Models.BillStatus", b =>
                {
                    b.Property<int>("BillStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.HasKey("BillStatusId");

                    b.ToTable("BillStatuses");

                    b.HasData(
                        new
                        {
                            BillStatusId = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            BillStatusId = 2,
                            Status = "Paid"
                        });
                });

            modelBuilder.Entity("BasicBilling.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "WATER"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "ELECTRICITY"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "SEWER"
                        });
                });

            modelBuilder.Entity("BasicBilling.API.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Name = "Joseph Carlton"
                        },
                        new
                        {
                            ClientId = 2,
                            Name = "Maria Juarez"
                        },
                        new
                        {
                            ClientId = 3,
                            Name = "Albert Kenny"
                        },
                        new
                        {
                            ClientId = 4,
                            Name = "Jessica Phillips"
                        },
                        new
                        {
                            ClientId = 5,
                            Name = " Charles Johnson"
                        });
                });

            modelBuilder.Entity("BasicBilling.API.Models.Payment", b =>
                {
                    b.Property<int>("PayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Client_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(25);

                    b.HasKey("PayId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PayId = 1,
                            Category_Id = 1,
                            Client_Id = 1,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 2,
                            Category_Id = 1,
                            Client_Id = 1,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 3,
                            Category_Id = 2,
                            Client_Id = 1,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 4,
                            Category_Id = 2,
                            Client_Id = 1,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 5,
                            Category_Id = 3,
                            Client_Id = 1,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 6,
                            Category_Id = 3,
                            Client_Id = 1,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 7,
                            Category_Id = 1,
                            Client_Id = 2,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 8,
                            Category_Id = 1,
                            Client_Id = 2,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 9,
                            Category_Id = 2,
                            Client_Id = 2,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 10,
                            Category_Id = 2,
                            Client_Id = 2,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 11,
                            Category_Id = 3,
                            Client_Id = 2,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 12,
                            Category_Id = 3,
                            Client_Id = 2,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 13,
                            Category_Id = 1,
                            Client_Id = 3,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 14,
                            Category_Id = 1,
                            Client_Id = 3,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 15,
                            Category_Id = 2,
                            Client_Id = 3,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 16,
                            Category_Id = 2,
                            Client_Id = 3,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 17,
                            Category_Id = 3,
                            Client_Id = 3,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 18,
                            Category_Id = 3,
                            Client_Id = 3,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 19,
                            Category_Id = 1,
                            Client_Id = 4,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 20,
                            Category_Id = 1,
                            Client_Id = 4,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 21,
                            Category_Id = 2,
                            Client_Id = 4,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 22,
                            Category_Id = 2,
                            Client_Id = 4,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 23,
                            Category_Id = 3,
                            Client_Id = 4,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 24,
                            Category_Id = 3,
                            Client_Id = 4,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 25,
                            Category_Id = 1,
                            Client_Id = 5,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 26,
                            Category_Id = 1,
                            Client_Id = 5,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 27,
                            Category_Id = 2,
                            Client_Id = 5,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 28,
                            Category_Id = 2,
                            Client_Id = 5,
                            Period = 202102
                        },
                        new
                        {
                            PayId = 29,
                            Category_Id = 3,
                            Client_Id = 5,
                            Period = 202101
                        },
                        new
                        {
                            PayId = 30,
                            Category_Id = 3,
                            Client_Id = 5,
                            Period = 202102
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
